// Code generated by protoc-gen-go.
// source: github.com/yarbelk/todo/store/store.proto
// DO NOT EDIT!

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	github.com/yarbelk/todo/store/store.proto

It has these top-level messages:
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import todo "github.com/yarbelk/todo"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Storer service

type StorerClient interface {
	Save(ctx context.Context, in *todo.TaskDefinition, opts ...client.CallOption) (*todo.TaskDefinition, error)
	Load(ctx context.Context, in *todo.TaskID, opts ...client.CallOption) (*todo.TaskDefinition, error)
	All(ctx context.Context, in *todo.AllTasksParams, opts ...client.CallOption) (*todo.TaskList, error)
}

type storerClient struct {
	c           client.Client
	serviceName string
}

func NewStorerClient(serviceName string, c client.Client) StorerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "storer"
	}
	return &storerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *storerClient) Save(ctx context.Context, in *todo.TaskDefinition, opts ...client.CallOption) (*todo.TaskDefinition, error) {
	req := c.c.NewRequest(c.serviceName, "Storer.Save", in)
	out := new(todo.TaskDefinition)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storerClient) Load(ctx context.Context, in *todo.TaskID, opts ...client.CallOption) (*todo.TaskDefinition, error) {
	req := c.c.NewRequest(c.serviceName, "Storer.Load", in)
	out := new(todo.TaskDefinition)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storerClient) All(ctx context.Context, in *todo.AllTasksParams, opts ...client.CallOption) (*todo.TaskList, error) {
	req := c.c.NewRequest(c.serviceName, "Storer.All", in)
	out := new(todo.TaskList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Storer service

type StorerHandler interface {
	Save(context.Context, *todo.TaskDefinition, *todo.TaskDefinition) error
	Load(context.Context, *todo.TaskID, *todo.TaskDefinition) error
	All(context.Context, *todo.AllTasksParams, *todo.TaskList) error
}

func RegisterStorerHandler(s server.Server, hdlr StorerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Storer{hdlr}, opts...))
}

type Storer struct {
	StorerHandler
}

func (h *Storer) Save(ctx context.Context, in *todo.TaskDefinition, out *todo.TaskDefinition) error {
	return h.StorerHandler.Save(ctx, in, out)
}

func (h *Storer) Load(ctx context.Context, in *todo.TaskID, out *todo.TaskDefinition) error {
	return h.StorerHandler.Load(ctx, in, out)
}

func (h *Storer) All(ctx context.Context, in *todo.AllTasksParams, out *todo.TaskList) error {
	return h.StorerHandler.All(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/yarbelk/todo/store/store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xaf, 0x4c, 0x2c, 0x4a, 0x4a, 0xcd, 0xc9, 0xd6, 0x2f,
	0xc9, 0x4f, 0xc9, 0xd7, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x85, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x52, 0x4a, 0xb8, 0x94, 0x96, 0x24, 0x16, 0x67, 0x43, 0xd4, 0x18, 0xcd, 0x66, 0xe4, 0x62,
	0x0b, 0x06, 0xe9, 0x29, 0x12, 0x32, 0xe1, 0x62, 0x09, 0x4e, 0x2c, 0x4b, 0x15, 0x12, 0xd1, 0x03,
	0x29, 0xd2, 0x0b, 0x49, 0x2c, 0xce, 0x76, 0x49, 0x4d, 0xcb, 0xcc, 0xcb, 0x2c, 0xc9, 0xcc, 0xcf,
	0x93, 0xc2, 0x2a, 0xaa, 0xc4, 0x20, 0xa4, 0xc3, 0xc5, 0xe2, 0x93, 0x9f, 0x98, 0x22, 0xc4, 0x83,
	0x90, 0xf7, 0x74, 0xc1, 0xa9, 0x5a, 0x97, 0x8b, 0xd9, 0x31, 0x27, 0x07, 0x66, 0x85, 0x63, 0x4e,
	0x0e, 0x48, 0x45, 0x71, 0x40, 0x62, 0x51, 0x62, 0x6e, 0xb1, 0x14, 0x1f, 0x42, 0x93, 0x4f, 0x66,
	0x71, 0x89, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x91, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0x07, 0x3c, 0x6f, 0xf5, 0x00, 0x00, 0x00,
}
